name: Ejecutar Script Python

on:
  schedule:
    # Ejecutar todos los días a las 6:00 PM hora Perú (23:00 UTC)
    - cron: '0 23 * * *'

    # Si quieres cambiar a las 8:00 AM hora Perú (13:00 UTC), descomenta esta línea y comenta la de arriba
    # - cron: '0 13 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script
        run: python timesheet.py
